export enum AuthErrorCode {
  INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS = 'AUTH_EMAIL_ALREADY_EXISTS',

  MISSING_ACCESS_TOKEN = 'AUTH_MISSING_ACCESS_TOKEN',
  INVALID_ACCESS_TOKEN = 'AUTH_INVALID_ACCESS_TOKEN',

  MISSING_REFRESH_TOKEN = 'AUTH_MISSING_REFRESH_TOKEN',
  INVALID_REFRESH_TOKEN = 'AUTH_INVALID_REFRESH_TOKEN',
  SESSION_REVOKED = 'AUTH_SESSION_REVOKED',
  SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',
  REFRESH_REUSE_DETECTED = 'AUTH_REFRESH_REUSE_DETECTED',

  USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
}
